baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Project'

[menus]

  [[menus.main]]
    URL = 'https://forum.creativecodingdetroit.org/'
    name = 'Forum'
    weight = 20

  [[menus.contact]]
    URL = 'https://www.instagram.com/creativecodingdetroit/'
    name = 'Instagram'
    weight = 10
    [menus.contact.params]
      icon = '/icons/icon-instagram.svg'
  [[menus.contact]]
    url =  'https://substack.com/@creativecodingdetroit'
    name = 'Substack'
    weight = 20
    [menus.contact.params]
      icon = '/icons/icon-substack.svg'
  [[menus.contact]]
    url = 'https://www.are.na/creative-coding-detroit/channels'
    name = 'Are.na'
    weight = 30
    [menus.contact.params]
      icon = '/icons/icon-arena.svg'
  [[menus.contact]]
    name = 'ccdet [at] proton.me'
    weight = 40
    [menus.contact.params]
      icon = '/icons/icon-email.svg'

[taxonomies]
  tag = 'tags'





